/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.Premio;
import datos.SorteoBDManager;
import datos.Validate;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class InicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InicioGeneral
     */
    public InicioAdmin() {
        initComponents();
        homePanel.setVisible(true);
        checkPanel.setVisible(false);
        statPanel.setVisible(false);
        winPanel.setVisible(false);
        losePanel.setVisible(false);
        statGenerator();
        checkExistingSorteos();
    }
    
    public InicioAdmin(int i) {
        initComponents();
        homePanel.setVisible(true);
        checkPanel.setVisible(false);
        statPanel.setVisible(false);
        winPanel.setVisible(false);
        losePanel.setVisible(false);
        statGenerator();
        checkExistingSorteos();
        if(i == 1)
            jButton3.setVisible(false);
    }
    
    private void statGenerator(){
        SorteoBDManager manager = new SorteoBDManager();
        statMasJugadoTable.setModel(manager.getStatMasJugados());
        statNumMonetario.setModel(manager.getStatMasPremiadoGen());
        statMasGanadoPP.setModel(manager.getStatGanadoMayorGen());
        statProb.setModel(manager.getStatPercentage());
    }
    
    private void checkExistingSorteos(){
        SorteoBDManager manager = new SorteoBDManager();
        ArrayList<String> last = manager.lastSorteo("1");
        if(last.size() == 2)
            chancesHomeFill(last.get(0),last.get(1),manager.topPremios(last.get(0)));
        last = manager.lastSorteo("2");
        if(last.size() == 2)
            loteriaHomeFill(last.get(0),last.get(1),manager.topPremios(last.get(0)));
    }
    
    private void chancesHomeFill(String sorteo,String date,ArrayList<Premio> data){
        chanceCode.setText("Sorteo "+sorteo);
        chanceDate.setText("Fecha de Juego: "+date);
        prNum.setText(data.get(0).getNombre());
        prSer.setText(data.get(0).getCantidad());
        prPrem.setText("₡"+data.get(0).getGanancia()+" por entero");
        sgNum.setText(data.get(1).getNombre());
        sgSer.setText(data.get(1).getCantidad());
        sgPrem.setText("₡"+data.get(1).getGanancia()+" por entero");
        trNum.setText(data.get(2).getNombre());
        trSer.setText(data.get(2).getCantidad());
        trPrem.setText("₡"+data.get(2).getGanancia()+" por entero");
    }
    
    private void loteriaHomeFill(String sorteo,String date,ArrayList<Premio> data){
        loteriaCode.setText("Sorteo "+sorteo);
        loteriaDate.setText("Fecha de Juego: "+date);
        prNumL.setText(data.get(0).getNombre());
        prSerL.setText(data.get(0).getCantidad());
        prPremL.setText("₡"+data.get(0).getGanancia()+" por entero");
        sgNumL.setText(data.get(1).getNombre());
        sgSerL.setText(data.get(1).getCantidad());
        sgPremL.setText("₡"+data.get(1).getGanancia()+" por entero");
        trNumL.setText(data.get(2).getNombre());
        trSerL.setText(data.get(2).getCantidad());
        trPremL.setText("₡"+data.get(2).getGanancia()+" por entero");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statPanel = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        statProb = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        statMasJugadoTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        statMasGanadoPP = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        statNumMonetario = new javax.swing.JTable();
        jLabel59 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel99 = new javax.swing.JLabel();
        checkPanel = new javax.swing.JPanel();
        losePanel = new javax.swing.JPanel();
        btnVolverL = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        winPanel = new javax.swing.JPanel();
        btnVolverW = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        winPremio = new javax.swing.JLabel();
        winSerie = new javax.swing.JLabel();
        winNum = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        checkBillPanel = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        tryFracc = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        tryCode = new javax.swing.JTextField();
        tryType = new javax.swing.JComboBox<>();
        btnCheckNumbers = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        trySerie = new javax.swing.JTextField();
        tryNum = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loteriaCode = new javax.swing.JLabel();
        loteriaDate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prNumL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prSerL = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        prPremL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sgNumL = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sgSerL = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sgPremL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        trNumL = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        trSerL = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        trPremL = new javax.swing.JLabel();
        chanceCode = new javax.swing.JLabel();
        chanceDate = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        prNum = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        prSer = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        prPrem = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        sgNum = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        sgSer = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        sgPrem = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        trNum = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        trSer = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        trPrem = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setBackground(new java.awt.Color(21, 57, 90));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("CERRAR SESIÓN");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 41, 65), 1, true));
        jButton12.setContentAreaFilled(false);
        jButton12.setFocusPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 120, 30));

        jButton1.setBackground(new java.awt.Color(21, 57, 90));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VER ESTADISTICAS");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 41, 65), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 160, 50));

        jButton4.setBackground(new java.awt.Color(21, 57, 90));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("INICIO");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 41, 65)));
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, 50));

        jButton5.setBackground(new java.awt.Color(21, 57, 90));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("VERIFICAR BILLETE");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 41, 65)));
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 50));

        jButton3.setBackground(new java.awt.Color(21, 57, 90));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADMINISTRACIÓN");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 41, 65), 1, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 160, 50));

        jLabel3.setBackground(new java.awt.Color(21, 57, 90));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1260, 50));

        jLabel2.setBackground(new java.awt.Color(16, 47, 75));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1260, 130));

        statPanel.setOpaque(false);
        statPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Probabilidades de números ");
        statPanel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, 30));

        statProb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(statProb);

        statPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 290, 190));

        statMasJugadoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Veces Jugado"
            }
        ));
        jScrollPane1.setViewportView(statMasJugadoTable);

        statPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 290, 190));

        statMasGanadoPP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Premio Total"
            }
        ));
        jScrollPane2.setViewportView(statMasGanadoPP);

        statPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 280, 110));

        statNumMonetario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Veces Ganadas"
            }
        ));
        jScrollPane3.setViewportView(statNumMonetario);

        statPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 290, 110));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel59.setText("Tipo de Sorteo:");
        statPanel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Lotería", "Chances" }));
        statPanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 130, 30));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel55.setText("Tipo de Sorteo:");
        statPanel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Lotería", "Chances" }));
        statPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 130, 30));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Top 5 números más ganadores del premio mayor");
        statPanel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Top 10 números más jugados");
        statPanel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, 30));

        jLabel100.setBackground(new java.awt.Color(255, 51, 51));
        jLabel100.setOpaque(true);
        statPanel.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 1100, 40));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Estadisticas");
        statPanel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Top 5 números mas premiados por valor monetario");
        statPanel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, 30));

        jLabel98.setBackground(new java.awt.Color(255, 51, 51));
        jLabel98.setOpaque(true);
        statPanel.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1100, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        statPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 30, 510));

        jLabel99.setBackground(new java.awt.Color(255, 255, 255));
        jLabel99.setOpaque(true);
        statPanel.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1100, 520));

        getContentPane().add(statPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1140, 580));

        checkPanel.setOpaque(false);
        checkPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        losePanel.setOpaque(false);
        losePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverL.setBackground(new java.awt.Color(255, 51, 51));
        btnVolverL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolverL.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverL.setText("VOLVER");
        btnVolverL.setBorderPainted(false);
        btnVolverL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        losePanel.add(btnVolverL, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 110, 30));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("del sorteo ingresado.");
        losePanel.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 420, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sad.gif"))); // NOI18N
        losePanel.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setText("El billete ingresado no ha ganado ningun premio");
        losePanel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel62.setText("Lo sentimos...");
        losePanel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Verificar Billete");
        losePanel.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel95.setBackground(new java.awt.Color(255, 255, 255));
        jLabel95.setOpaque(true);
        losePanel.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 690, 410));

        checkPanel.add(losePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        winPanel.setOpaque(false);
        winPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverW.setBackground(new java.awt.Color(255, 51, 51));
        btnVolverW.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVolverW.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverW.setText("VOLVER");
        btnVolverW.setBorderPainted(false);
        btnVolverW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        winPanel.add(btnVolverW, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 110, 30));

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/firework.gif"))); // NOI18N
        winPanel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 180, 160));

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/firework.gif"))); // NOI18N
        winPanel.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 180, 160));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/danceMan.gif"))); // NOI18N
        winPanel.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 200, -1));

        winPremio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        winPremio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winPremio.setText("Tu premio es: ");
        winPanel.add(winPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 490, -1));

        winSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        winSerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winSerie.setText("Serie:");
        winPanel.add(winSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 100, -1));

        winNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        winNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winNum.setText("Número:");
        winPanel.add(winNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 100, -1));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel69.setText("Tu billete es el ganador de un premio del sorteo ingresado");
        winPanel.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel70.setText("¡Felicidades!");
        winPanel.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Verificar Billete");
        winPanel.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel96.setBackground(new java.awt.Color(255, 255, 255));
        jLabel96.setOpaque(true);
        winPanel.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 690, 410));

        checkPanel.add(winPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        checkBillPanel.setOpaque(false);
        checkBillPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setText("Fracciones:");
        checkBillPanel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));
        checkBillPanel.add(tryFracc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 130, 30));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setText("Número de Sorteo:");
        checkBillPanel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel60.setText("Tipo de Sorteo:");
        checkBillPanel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));
        checkBillPanel.add(tryCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 30));

        tryType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lotería", "Chances" }));
        checkBillPanel.add(tryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 130, 30));

        btnCheckNumbers.setBackground(new java.awt.Color(255, 51, 51));
        btnCheckNumbers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckNumbers.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckNumbers.setText("VERIFICAR");
        btnCheckNumbers.setBorderPainted(false);
        btnCheckNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckNumbersActionPerformed(evt);
            }
        });
        checkBillPanel.add(btnCheckNumbers, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 150, 40));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel51.setText("Serie");
        checkBillPanel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setText("Número");
        checkBillPanel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        trySerie.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        checkBillPanel.add(trySerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 100, 100));

        tryNum.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        checkBillPanel.add(tryNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 100, 100));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Verificar Billete");
        checkBillPanel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel94.setBackground(new java.awt.Color(255, 255, 255));
        jLabel94.setOpaque(true);
        checkBillPanel.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 690, 410));

        checkPanel.add(checkBillPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 580));

        getContentPane().add(checkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1140, 580));

        homePanel.setOpaque(false);
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ultimos Resultados ");
        homePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lotería");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chances");
        homePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        loteriaCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loteriaCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loteriaCode.setText("Sorteo ---");
        homePanel.add(loteriaCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 390, 20));

        loteriaDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loteriaDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loteriaDate.setText("Aun no se ha jugado ningun sorteo de loteria");
        homePanel.add(loteriaDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 390, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Primer Premio");
        homePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        prNumL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prNumL.setText("--");
        homePanel.add(prNumL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 20, 30));

        jLabel18.setText("Número");
        homePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        prSerL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prSerL.setText("---");
        homePanel.add(prSerL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, 30));

        jLabel19.setText("Serie");
        homePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        prPremL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(prPremL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 260, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Segundo Premio");
        homePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        sgNumL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgNumL.setText("--");
        homePanel.add(sgNumL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 20, 30));

        jLabel21.setText("Número");
        homePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        sgSerL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgSerL.setText("---");
        homePanel.add(sgSerL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, 30));

        jLabel23.setText("Serie");
        homePanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        sgPremL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(sgPremL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 260, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Tercer Premio");
        homePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        trNumL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trNumL.setText("--");
        homePanel.add(trNumL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 20, 30));

        jLabel26.setText("Número");
        homePanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        trSerL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trSerL.setText("---");
        homePanel.add(trSerL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, 30));

        jLabel28.setText("Serie");
        homePanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        trPremL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(trPremL, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 270, 20));

        chanceCode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chanceCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chanceCode.setText("Sorteo ---");
        homePanel.add(chanceCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 140, 400, 20));

        chanceDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chanceDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chanceDate.setText("Aun no se ha jugado ningun sorteo de chances");
        homePanel.add(chanceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 400, 20));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setText("Primer Premio");
        homePanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        prNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prNum.setText("--");
        homePanel.add(prNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 20, 30));

        jLabel34.setText("Número");
        homePanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        prSer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prSer.setText("---");
        homePanel.add(prSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, 30));

        jLabel36.setText("Serie");
        homePanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, -1));

        prPrem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(prPrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 270, 20));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setText("Segundo Premio");
        homePanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        sgNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgNum.setText("--");
        homePanel.add(sgNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 20, 30));

        jLabel40.setText("Número");
        homePanel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        sgSer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sgSer.setText("---");
        homePanel.add(sgSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, -1, 30));

        jLabel42.setText("Serie");
        homePanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        sgPrem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(sgPrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 270, 20));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setText("Tercer Premio");
        homePanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        trNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trNum.setText("--");
        homePanel.add(trNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 20, 30));

        jLabel46.setText("Número");
        homePanel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, -1));

        trSer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trSer.setText("---");
        homePanel.add(trSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, 30));

        jLabel48.setText("Serie");
        homePanel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        trPrem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homePanel.add(trPrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 270, 20));

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setOpaque(true);
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1100, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        homePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 30, 520));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        homePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1100, 520));

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 1140, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lottery (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1260, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        homePanel.setVisible(false);
        checkPanel.setVisible(true);
        statPanel.setVisible(false);
        checkPanel.setBounds(60,160,1140,580);
        winPanel.setVisible(false);
        losePanel.setVisible(false);
        checkBillPanel.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        Color color = new Color(17,46,72);
        jButton4.setBackground(color);
        jButton4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        Color color = new Color(21,57,90);
        jButton4.setBackground(color);
        jButton4.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        homePanel.setVisible(true);
        checkPanel.setVisible(false);
        statPanel.setVisible(false);
        homePanel.setBounds(60,160,1140,580);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homePanel.setVisible(false);
        checkPanel.setVisible(false);
        statPanel.setVisible(true);
        statPanel.setBounds(60,160,1140,580);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminSide secondForm = new AdminSide();
        secondForm.show();

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Login secondForm = new Login();
        secondForm.show();

        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnCheckNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckNumbersActionPerformed
        SorteoBDManager manager = new SorteoBDManager();
        String errors = Validate.validateCheck(tryCode.getText(), tryNum.getText(), trySerie.getText(), tryFracc.getText());
        if(errors.equals("")){
            double amount = manager.checkWin(tryCode.getText(), tryNum.getText(), trySerie.getText());
            if(amount==0){
                checkBillPanel.setVisible(false);
                losePanel.setVisible(true);
            }
            else{
                winNum.setText("Número: "+tryNum.getText());
                winSerie.setText("Serie: "+trySerie.getText());
                winPremio.setText("Tu premio es: ₡"+amount);
                checkBillPanel.setVisible(false);
                winPanel.setVisible(true);
            }
        }
        else
            JOptionPane.showMessageDialog(null,errors, "Error con datos ingresados", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCheckNumbersActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        winPanel.setVisible(false);
        losePanel.setVisible(false);
        checkBillPanel.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckNumbers;
    private javax.swing.JButton btnVolverL;
    private javax.swing.JButton btnVolverW;
    private javax.swing.JLabel chanceCode;
    private javax.swing.JLabel chanceDate;
    private javax.swing.JPanel checkBillPanel;
    private javax.swing.JPanel checkPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel losePanel;
    private javax.swing.JLabel loteriaCode;
    private javax.swing.JLabel loteriaDate;
    private javax.swing.JLabel prNum;
    private javax.swing.JLabel prNumL;
    private javax.swing.JLabel prPrem;
    private javax.swing.JLabel prPremL;
    private javax.swing.JLabel prSer;
    private javax.swing.JLabel prSerL;
    private javax.swing.JLabel sgNum;
    private javax.swing.JLabel sgNumL;
    private javax.swing.JLabel sgPrem;
    private javax.swing.JLabel sgPremL;
    private javax.swing.JLabel sgSer;
    private javax.swing.JLabel sgSerL;
    private javax.swing.JTable statMasGanadoPP;
    private javax.swing.JTable statMasJugadoTable;
    private javax.swing.JTable statNumMonetario;
    private javax.swing.JPanel statPanel;
    private javax.swing.JTable statProb;
    private javax.swing.JLabel trNum;
    private javax.swing.JLabel trNumL;
    private javax.swing.JLabel trPrem;
    private javax.swing.JLabel trPremL;
    private javax.swing.JLabel trSer;
    private javax.swing.JLabel trSerL;
    private javax.swing.JTextField tryCode;
    private javax.swing.JTextField tryFracc;
    private javax.swing.JTextField tryNum;
    private javax.swing.JTextField trySerie;
    private javax.swing.JComboBox<String> tryType;
    private javax.swing.JLabel winNum;
    private javax.swing.JPanel winPanel;
    private javax.swing.JLabel winPremio;
    private javax.swing.JLabel winSerie;
    // End of variables declaration//GEN-END:variables
}
